version: "3"
services:
  php8.0:
    build:
      context: ./php
      dockerfile: 8.0.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "projects:/var/www/html"
    depends_on:
      - mysql

  php7.4:
    build:
      context: ./php
      dockerfile: 7.4.Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - "projects:/var/www/html"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php7.4"
      - "php8.0"
    volumes:
      - "projects:/var/www/html"
      - "./nginx/config:/etc/nginx/conf.d"

  # mariadb:
  #   image: mariadb:10.3.9
  #   container_name: mariadb
  #   restart: "on-failure"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   volumes:
  #     - ${PWD}

  mysql:
    image: mysql
    volumes:
      - "../database/mysql:/var/lib/mysql"
      - "desktop:/root"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=200M

volumes:
  projects:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data/Users/sonhaichu/Projects"
  desktop:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data/Users/sonhaichu/Desktop"
