version: "3"
services:
  php8.0:
    build:
      context: ./php
      dockerfile: 8.0.Dockerfile
    ports:
      - "8000:8000"
    extra_hosts:
      - "zabbix.local:192.168.24.215"
    volumes:
      - "projects:/var/www/html"
    depends_on:
      - mysql

  php7.4:
    build:
      context: ./php
      dockerfile: 7.4.Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - "projects:/var/www/html"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php7.4"
      - "php8.0"
    volumes:
      - "projects:/var/www/html"
      - "./nginx/config:/etc/nginx/conf.d"

  # mariadb:
  #   image: mariadb:10.3.9
  #   container_name: mariadb
  #   restart: "on-failure"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   volumes:
  #     - ${PWD}

  mysql:
    image: mysql:8
    volumes:
      - "../database/mysql:/var/lib/mysql"
      - "desktop:/root"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=200M

  mongo:
    image: mongo:6
    volumes:
      - "../database/mongo:/data/db"
      - "desktop:/home"
    ports:
      - "27017:27017"
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  postgres:
    image: postgres:14
    volumes:
      - "../database/postgres:/var/lib/postgresql/data"
      - "desktop:/home"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}

  redis:
    image: redis:7
    volumes:
      - "../database/redis:/data"
    ports:
      - "6379:6379"

volumes:
  projects:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data/Users/sonhaichu/Projects"
  desktop:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data/Users/sonhaichu/Desktop"
