version: "3"
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "8000:8000"
    volumes:
      - "..:/var/www/html"
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php"
    volumes:
      - "./app:/var/www/html"
      - "./nginx/config:/etc/nginx/conf.d"

  mariadb:
    image: mariadb:10.3.9
    container_name: mariadb
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${PWD}
