version: "3"
services:
  php:
    build:
      context: ./php
      dockerfile: 7.4.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "..:/var/www/html"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php"
    volumes:
      - "..:/var/www/html"
      - "./nginx/config:/etc/nginx/conf.d"

  # mariadb:
  #   image: mariadb:10.3.9
  #   container_name: mariadb
  #   restart: "on-failure"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   volumes:
  #     - ${PWD}

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 3307:80
    environment:
      - PMA_ARBITRARY=1
